export enum EGenericComponentType {
  Button    = 'button',
  Text      = 'text',
  Heading   = 'heading',
  Subheading = 'subheading',
  Image     = 'image',
  Icon      = 'icon',
  Badge     = 'badge',
  Tag       = 'tag',
  Card      = 'card',
  Container = 'container',
  Grid      = 'grid',
  Row       = 'row',
  Column    = 'column',
  Divider   = 'divider',
  Spacer    = 'spacer',
  Input     = 'input',
  List      = 'list',
  ListItem  = 'list-item',
  Link      = 'link',
  Video     = 'video',
  Carousel  = 'carousel',
}
