export enum EGenericComponentType {
  Button   = 'vf-button',
  Text     = 'vf-text',
  Heading  = 'vf-heading',
  Img      = 'vf-img',
  Icon     = 'vf-icon',
  Chip     = 'vf-chip',
  Box      = 'vf-box',
  Divider  = 'vf-divider',
  Carousel = 'vf-carousel',
  Video    = 'vf-video',
  Tag      = 'vf-tag',
  Card     = 'vf-card',
  Container = 'vf-container',
  Grid     = 'vf-grid',
  Row      = 'vf-row',
  Column   = 'vf-column',
  Spacer   = 'vf-spacer',
  Input    = 'vf-input',
  List     = 'vf-list',
  ListItem = 'vf-list-item',
  Link     = 'vf-link',
}
