import { EGenericComponentType } from '../enums/generic-component-type.enum'

export const GENERIC_COMPONENT_LABELS: Record<EGenericComponentType, string> = {
  [EGenericComponentType.Button]:    'Bouton',
  [EGenericComponentType.Text]:      'Texte',
  [EGenericComponentType.Heading]:   'Titre',
  [EGenericComponentType.Img]:       'Image',
  [EGenericComponentType.Icon]:      'Icône',
  [EGenericComponentType.Chip]:      'Chip / Badge',
  [EGenericComponentType.Box]:       'Box / Carte',
  [EGenericComponentType.Divider]:   'Séparateur',
  [EGenericComponentType.Carousel]:  'Carrousel',
  [EGenericComponentType.Video]:     'Vidéo',
  [EGenericComponentType.Tag]:       'Tag',
  [EGenericComponentType.Card]:      'Carte',
  [EGenericComponentType.Container]: 'Conteneur',
  [EGenericComponentType.Grid]:      'Grille',
  [EGenericComponentType.Row]:       'Ligne',
  [EGenericComponentType.Column]:    'Colonne',
  [EGenericComponentType.Spacer]:    'Espaceur',
  [EGenericComponentType.Input]:     'Champ de saisie',
  [EGenericComponentType.List]:      'Liste',
  [EGenericComponentType.ListItem]:  'Élément de liste',
  [EGenericComponentType.Link]:      'Lien',
}
